IF DB_ID('RaceDay_PoE_Final') IS NOT NULL
BEGIN
    ALTER DATABASE RaceDay_PoE_Final
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE RaceDay_PoE_Final;
END;
GO

CREATE DATABASE RaceDay_PoE_Final;
GO